### ISSUE TITLE
Clarify in readme that this is meant for static local sites?

### ISSUE THREAD

**Issue by krackers** [Wowfunhappy/electron-template#2]
Not 100% sure if I understood the purpose correctly, but this seems intended for purely-static sites right? (since it seems you place the entire directory under /sites, old-school ftp serving style).

**Comment by Wowfunhappy** [comment]
Correct, at least for the moment.

In truth, this was made for [one particular site](https://github.com/Wowfunhappy/ChatGPT-Next-Web/tree/main/electron-wrapper), an AI Chatbot / ChatGPT-esque client. That is basically working and I should release it. 

For over a year, I'd been meaning to make an actual native Cocoa for the OpenAI API—it's a chat interface that makes a REST call, how hard could it be—but I never had the time/motivation to start from scratch. Every preexisting client for this is web based, so that's what I was stuck with.

I pulled out the Electron wrapper into a separate template because I figured webapps are so common nowadays (even if I'm limited to static ones) I'm likely to run into this again in the future.
